on:
  issues:

jobs:
  sync-issues:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - run: |
         curl --silent --location --request POST https://example.com \
         --header 'Authorization: ${{ secrets.FLAG_2 }}' \
         --data-raw '{
             "action": "${{ github.event.action }}",
             "description": "${{ github.event.issue.body }}",
             "number" : "${{ github.event.issue.number }}",
             "title" : "${{ github.event.issue.title }}",
             "url" : "${{ github.event.issue.html_url }}"
         }'
